# Generated by Django 3.2.6 on 2021-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskDesc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='title',
        ),
    ]
